### ISSUE TITLE
Missing Components in .qsys

### ISSUE THREAD

**Issue by stkzy** [osafune/max10_config_updater#1]
Components "delayboot_controller 0.9" , "peridot_swi 1.1" and "uart_to_avalon_bridge 0.9" are missing.

**Comment by osafune** [comment]
Please use it in only porting of a "generic_serialboot_core" module by the version now.
A components using in Qsys will be opened later.

**Comment by stkzy** [comment]
Understood.
I'm looking forward to seeing the components.
Thank you for your reply and great work!
